<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Booking Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 12px;
      margin: 20px;
    }
    h1 {
      text-align: center;
      font-size: 18px;
      margin-bottom: 5px;
    }
    .meta {
      text-align: center;
      color: #666;
      font-size: 10px;
      margin-bottom: 20px;
    }
    .summary {
      display: flex;
      justify-content: space-between;
      margin-bottom: 20px;
      border: 1px solid #ddd;
      padding: 10px;
    }
    .summary-box {
      text-align: center;
      flex: 1;
    }
    .summary-label {
      font-size: 10px;
      color: #666;
    }
    .summary-value {
      font-size: 16px;
      font-weight: bold;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 6px;
      text-align: left;
    }
    th {
      background-color: #f5f5f5;
      font-weight: bold;
    }
    .text-right {
      text-align: right;
    }
    .text-center {
      text-align: center;
    }
    .filters {
      margin-bottom: 15px;
      padding: 8px;
      background-color: #f9f9f9;
      border: 1px solid #eee;
      font-size: 10px;
    }
    @media print {
      body { margin: 10px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="text-align: center; margin-bottom: 20px;">
    <button onclick="window.print()" style="padding: 10px 20px; font-size: 14px;">
      <i class="nav-icon icon-printer"></i> Print Report
    </button>
    <button onclick="window.close()" style="padding: 10px 20px; font-size: 14px; margin-left: 10px;">
      Close
    </button>
  </div>

  <h1>Booking Report</h1>
  <div class="meta">
    Generated by: {{ $generated_by }} | Generated at: {{ $generated_at }}
  </div>

  @if($filters['from_date'] || $filters['to_date'] || $filters['user_id'] || $filters['counter_id'])
  <div class="filters">
    <strong>Filters Applied:</strong>
    @if($filters['from_date']) From: {{ $filters['from_date'] }} @endif
    @if($filters['to_date']) To: {{ $filters['to_date'] }} @endif
    @if($filters['user_id'])
      @php
        $userName = \App\Models\User::find($filters['user_id']);
      @endphp
      | User: {{ $userName ? $userName->name : 'Unknown' }}
    @endif
    @if($filters['counter_id'])
      @php
        $counterName = \App\Models\Counter::find($filters['counter_id']);
      @endphp
      | Counter: {{ $counterName ? $counterName->name : 'Unknown' }}
    @endif
  </div>
  @endif

  <div class="summary">
    <div class="summary-box">
      <div class="summary-label">Total Bookings</div>
      <div class="summary-value">{{ $total_bookings }}</div>
    </div>
    <div class="summary-box">
      <div class="summary-label">Total Revenue</div>
      <div class="summary-value">৳{{ number_format($total_revenue, 2) }}</div>
    </div>
    <div class="summary-box">
      <div class="summary-label">Average per Booking</div>
      <div class="summary-value">
        ৳{{ $total_bookings > 0 ? number_format($total_revenue / $total_bookings, 2) : '0.00' }}
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>ID</th>
        <th>Date</th>
        <th>Service</th>
        <th>Guest Name</th>
        <th>Counter</th>
        <th>Created By</th>
        <th class="text-right">Amount</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      @php $i = 1; @endphp
      @forelse($bookings as $booking)
        <tr>
          <td>{{ $i++ }}</td>
          <td>{{ $booking->id }}</td>
          <td>{{ date('d-m-Y', strtotime($booking->check_in_date)) }}</td>
          <td>{{ $booking->service ? $booking->service->name : '-' }}</td>
          <td>{{ $booking->name ?? 'N/A' }}</td>
          <td>{{ $booking->counter ? $booking->counter->name : '-' }}</td>
          <td>{{ $booking->creator ? $booking->creator->name : '-' }}</td>
          <td class="text-right">৳{{ number_format($booking->final_price, 2) }}</td>
          <td>{{ config('myhelpers.booking_status')[$booking->status] ?? 'Unknown' }}</td>
        </tr>
      @empty
        <tr>
          <td colspan="9" class="text-center">No bookings found</td>
        </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <th colspan="8" class="text-right">Total:</th>
        <th class="text-right">৳{{ number_format($total_revenue, 2) }}</th>
        <th></th>
      </tr>
    </tfoot>
  </table>

  <script>
    // Auto-print when page loads (optional, can be removed if not desired)
    // window.onload = function() { window.print(); }
  </script>
</body>
</html>
