@section('footer')
<div style="margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px;">
    <div style="display: flex; justify-content: space-between;">
        <div>
            <p><strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }}</p>
            <p><strong>Generated On:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
        </div>
        <div class="text-right">
            <p><strong>Page:</strong> <span class="page-number"></span></p>
        </div>
    </div>
</div>
@endsection
